name: "Push Validation"

on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"

jobs:
  build-and-test:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        container:
        - "ocaml/opam2:alpine-3.8-ocaml-4.03"
        - "ocaml/opam2:alpine-3.12-ocaml-4.11"
    container:
      image: "${{ matrix.container }}"
      options: "--user root"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Prepare container environment"
      run: |
        apk add --no-cache m4 perl gmp-dev git
        chown -R opam .
        cd /home/opam/opam-repository
        sudo -u opam git fetch
        sudo -u opam git checkout 6ef290f5681b7ece5d9c085bcf0c55268c118292
        sudo -u opam opam update
    - name: "Build and test."
      shell: "sudo -u opam sh -e {0}"
      run: "opam install -y --with-test ."
    - name: "Check formatting"
      shell: "sudo -u opam sh -e {0}"
      run: |
        opam install -y ocp-indent
        eval $(opam env)
        find src test -name "*.ml" -or -name "*.mli" -type f | xargs ocp-indent -i
        git diff --exit-code
    - name: "Run benchmark"
      shell: "sudo -u opam sh -e {0}"
      run: |
        opam install -y benchmark
        eval $(opam env)
        dune exec benchmark/curveops.exe
    - name: "Build documentation"
      shell: "sudo -u opam sh -e {0}"
      run: |
        opam install -y odoc
        eval $(opam env)
        dune build @doc
    - name: "Push documentation"
      if: ${{ github.event_name == 'push' && matrix.container == 'ocaml/opam2:alpine-3.12-ocaml-4.11' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/default/_doc/_html
